### ISSUE TITLE
Where can I get the bin file you mentioned?

### ISSUE THREAD

**Issue by ericwind1978** [ethz-asl/sl_sensor#11]
Hi,
    I had read the tips you mentioned above, but when i setup the project , i can not find the file DLPR350PROM_v4.1.0_with_calibration_patterns_25x16.bin， and also the 4500 gui which version is 4.0.0， the ti version is 4.4， please help me , 3x very much , my email is  31948524@qq.com

**Comment by tengfoonglam** [comment]
Hi Eric,

Thank you for the email. The .bin file is located in another repository and unfortunately its access has been switched to Private some time ago and it will take a some time for me to make it available again since I do not have the required privileges to do that.

I have already contacted you in a separate email to provide the requested files.

I will close this issue once the repository is made public again. 

Thanks!

Yours sincerely,
Teng Foong Lam

**Comment by tengfoonglam** [comment]
The accessibility of the other repo has been fixed and the link in the Wiki is functional again. Closing this issue.
